.\" Man Page for gde2-volume-control-applet
.TH GDE2-VOLUME-CONTROL-APPLET 1 "20 February 2014" "GDE2 Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
\fBgde2-volume-control-applet\fR \- The GDE2 Volume Control Applet
.SH "SYNOPSIS"
.B gde2-volume-control [OPTIONS]
.SH "DESCRIPTION"
The GDE2 Volume Control Applet is used for adjusting audio levels from the notification area.
.SH "OPTIONS"
.TP
\fB\-v, \-\-version\fR
Output version information and exit.
.TP
\fB\-d, \-\-debug\fR
Enable debugging code.
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
\fB\-?, \-h, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.TP
This program also accepts the standard GTK+ options.
.TP
\fB\-\-help\-gtk\fR
Print GTK+ options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
http://github.com/gde2-desktop/gde2-media/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the GDE2 Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.gde2-desktop.org/docs
.BR gde2-volume-control (1)
